[tox]
envlist = flake8, py27, py34, py35, py36, py37, py38, pypy, pypy3
skip_missing_interpreters = true

[testenv]
deps =
    pytest<6 ; python_version < "3.0"
    pytest<5 ; python_version == "3.4"
    pytest ; python_version >= "3.5"
commands =
    pytest {posargs:tests}

[testenv:flake8]
skip_install = true
deps = flake8
commands = flake8 mylib tests
