[tox]
envlist = py27, py35, py36, py37, py38, flake8
skip_missing_interpreters = true
isolated_build = false

[testenv]
deps =
    pytest
    six
commands =
    pytest {posargs:tests}

[testenv:flake8]
basepython = python3
skip_install = true
skipdist = true
deps =
    flake8
commands =
    flake8 src tests setup.py
