version: 2

project_name: yul

before:
  hooks:
    - go mod tidy

builds:
  - id: yul
    binary: yul
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: yul
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^doc:"

release:
  github:
    owner: chains-project
    name: yul
