[tox]
envlist = py27, py34, py35, py36, py37, py38, pypy, pypy3, flake8
skip_missing_interpreters = true
isolated_build = false

[testenv]
deps =
    pytest>=4.6,<5.0; python_version < "3.5"
    pytest>=4.6,<7.0; python_version >= "3.5" and python_version < "3.6"
    pytest>=6.0; python_version >= "3.6"
    pytest-cov
commands =
    pytest --cov=mylib {posargs:tests}

[testenv:flake8]
basepython = python3
deps = flake8
commands = flake8 src tests setup.py

[testenv:docs]
basepython = python3
deps = sphinx
commands = sphinx-build -b html docs docs/_build

[pytest]
testpaths = tests
