[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "=1.0.195", features = ["derive"] }
winapi = { version = "0.3", features = ["winuser", "windef", "wincon", "winnt"] }
windows = { version = "0.52", features = ["Win32"] }
windows-sys = { version = "0.48", features = ["Win32"] }
windows-targets = { version = "0.48" }
windows-link = { version = "0.1" }
windows-result = { version = "0.1" }
windows-strings = { version = "0.1" }
windows-core = { version = "0.48" }
windows-implement = { version = "0.52" }
windows-interface = { version = "0.52" }