[tox]
envlist = py27, py35, py36, py37, py38, py39, py310, py311, pypy, pypy3
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps =
    pytest<5; python_version < '3'
    pytest>=6; python_version >= '3'
commands =
    pytest {posargs}

[testenv:flake8]
basepython = python3
skip_install = true
deps = flake8
commands =
    flake8 mylib tests

[flake8]
max-line-length = 100
exclude = .git,__pycache__,build,dist,.tox,.eggs
